import nike01 from './img/nike01.jpg'
import nike02 from './img/nike02.jpg'
import nike03 from './img/nike03.jpg'
import nike04 from './img/nike04.jpeg'
import nike05 from './img/nike05.jpg'
import nike06 from './img/nike06.jpg'
import nike07 from './img/nike07.jpg'
import adidas01 from './img/adidas01.jpg'

export const storeData = [
    {
      id: "1",
      img: nike01,
      name: "Nike Air Zoom Mercurial Vapor XV Pro TF",
      text: "Football boots for sinte",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["black", "white", "green"],
      gender: "male",
      price: 45,
    },
    {
      id: "2",
      img: nike02,
      name: "Nike Tiempo Legend X PRO TF",
      text: "",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["black", "red", "white"],
      gender: "male",
      price: 55,
    },
    {
      id: "3",
      img: nike03,
      name: "Nike Phantom GT Academy Dynamic Fit",
      text: "",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["green", "gray", "yellow"],
      gender: "male",
      price: 50,
    },
    {
      id: "4",
      img: nike04,
      name: "Nike Phantom Ultra Venom",
      text: "",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["green", "black", "white"],
      gender: "male",
      price: 50,
    },
    {
      id: "5",
      img: nike05,
      name: "Nike MagistaX Finale II",
      text: "",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["blue", "black", "white"],
      gender: "male",
      price: 50,
    },
    {
      id: "6",
      img: nike06,
      name: "Nike Air Zoom Mercurial Vapor",
      text: "",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["blue", "red", "white"],
      gender: "male",
      price: 50,
    },
    {
      id: "7",
      img: nike07,
      name: "Nike Air Zoom Mercurial Vapor",
      text: "",
      type: "Nike",
      size: ["39", "40", "41", "42"],
      color: ["blue", "red", "white"],
      gender: "male",
      price: 50,
    },
  
    {
      id: "8",
      img: adidas01,
      name: "Adidas Predator Edge.3",
      text: "",
      type: "Adidas",
      size: ["39", "40", "41", "42"],
      color: ["blue", "red", "white", 'black'],
      gender: "male",
      price: 50,
    },
  //   {
  //     id: "10",
  //     img: hoodie2,
  //     name: "Casual Hoodie 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "L", "XL"],
  //     color: ["gray", "purple", "black"],
  //     gender: "female",
  //     price: 95,
  //   },
  //   {
  //     id: "11",
  //     img: hoodie3,
  //     name: "Casual Hoodie 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "M", "XL"],
  //     color: ["red", "blue", "black"],
  //     gender: "male",
  //     price: 95,
  //   },
  //   {
  //     id: "12",
  //     img: hoodie4,
  //     name: "Casual Hoodie 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "XL"],
  //     color: ["gray", "blue", "red"],
  //     gender: "male",
  //     price: 125,
  //   },
  //   {
  //     id: "13",
  //     img: hoodie5,
  //     name: "Casual Hoodie 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "XL"],
  //     color: ["gray", "blue", "red"],
  //     gender: "female",
  //     price: 250,
  //   },
  //   {
  //     id: "14",
  //     img: hoodie6,
  //     name: "Casual Hoodie 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "XL"],
  //     color: ["gray", "yellow", "blue"],
  //     gender: "male",
  //     price: 125,
  //   },
  //   {
  //     id: "15",
  //     img: hoodie7,
  //     name: "Casual Hoodie 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "M", "L", "XL"],
  //     color: ["black", "blue"],
  //     gender: "male",
  //     price: 450,
  //   },
  //   {
  //     id: "16",
  //     img: hoodie8,
  //     name: "Casual Hoodie 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Hoodies",
  //     size: ["S", "M", "L", "XL"],
  //     color: ["green", "yellow", "red"],
  //     gender: "female",
  //     price: 355,
  //   },
  
  //   {
  //     id: "17",
  //     img: shoe5,
  //     name: "Casual Shoes 1",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["40", "42", "44", "46"],
  //     color: ["black", "gray"],
  //     gender: "male",
  //     price: 200,
  //   },
  //   {
  //     id: "18",
  //     img: shoe6,
  //     name: "Casual Shoes 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["40", "42", "44", "46"],
  //     color: ["brown", "gray"],
  //     gender: "female",
  //     price: 250,
  //   },
  //   {
  //     id: "19",
  //     img: shoe7,
  //     name: "Casual Shoes 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["36", "38", "40", "42"],
  //     color: ["black", "gray", "blue"],
  //     gender: "female",
  //     price: 685,
  //   },
  //   {
  //     id: "20",
  //     img: shoe8,
  //     name: "Casual Shoes 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["36", "38", "40", "42"],
  //     color: ["black", "gray"],
  //     gender: "male",
  //     price: 255,
  //   },
  //   {
  //     id: "21",
  //     img: shoe9,
  //     name: "Casual Shoes 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["36", "38", "40", "42"],
  //     color: ["purple", "gray", "black"],
  //     gender: "male",
  //     price: 355,
  //   },
  //   {
  //     id: "22",
  //     img: shoe10,
  //     name: "Casual Shoes 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["36", "38", "40", "42"],
  //     color: ["purple", "gray", "black"],
  //     gender: "male",
  //     price: 200,
  //   },
  //   {
  //     id: "23",
  //     img: shoe11,
  //     name: "Casual Shoes 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["36", "38", "40", "42"],
  //     color: ["purple", "green", "black"],
  //     gender: "male",
  //     price: 100,
  //   },
  //   {
  //     id: "24",
  //     img: shoe12,
  //     name: "Casual Shoes 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Shoes",
  //     size: ["36", "38", "40", "42"],
  //     color: ["purple", "green", "black"],
  //     gender: "male",
  //     price: 135,
  //   },
  //   {
  //     id: "25",
  //     img: dress1,
  //     name: "Casual Dress 1",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["L", "XL"],
  //     color: ["purple", "blue", "gray"],
  //     gender: "female",
  //     price: 355,
  //   },
  //   {
  //     id: "26",
  //     img: dress2,
  //     name: "Casual Dress 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["S", "M", "XL"],
  //     color: ["black", "gray", "green"],
  //     gender: "female",
  //     price: 255,
  //   },
  //   {
  //     id: "27",
  //     img: dress3,
  //     name: "Casual Dress 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["S", "M", "XL"],
  //     color: ["purple", "blue", "red"],
  //     gender: "female",
  //     price: 65,
  //   },
  //   {
  //     id: "28",
  //     img: dress4,
  //     name: "Casual Dress 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["S", "L", "XL"],
  //     color: ["yellow", "blue", "orange"],
  //     gender: "female",
  //     price: 185,
  //   },
  //   {
  //     id: "29",
  //     img: dress5,
  //     name: "Casual Dress 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["S", "L", "XL"],
  //     color: ["yellow", "orange"],
  //     gender: "female",
  //     price: 555,
  //   },
  //   {
  //     id: "30",
  //     img: dress6,
  //     name: "Casual Dress 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["S", "M"],
  //     color: ["yellow", "blue", "black"],
  //     gender: "female",
  //     price: 345,
  //   },
  //   {
  //     id: "31",
  //     img: dress7,
  //     name: "Casual Dress 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["S", "M"],
  //     color: ["orange", "blue", "black"],
  //     gender: "female",
  //     price: 345,
  //   },
  //   {
  //     id: "32",
  //     img: dress8,
  //     name: "Casual Dress 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Dresses",
  //     size: ["M", "L"],
  //     color: ["brown", "blue", "red"],
  //     gender: "female",
  //     price: 685,
  //   },
  //   {
  //     id: "33",
  //     img: jeans1,
  //     name: "Casual Jeans 1",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["S", "M", "L"],
  //     color: ["blue", "black"],
  //     gender: "male",
  //     price: 55,
  //   },
  //   {
  //     id: "34",
  //     img: jeans2,
  //     name: "Casual Jeans 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["S", "M"],
  //     color: ["blue", "black"],
  //     gender: "female",
  //     price: 75,
  //   },
  //   {
  //     id: "35",
  //     img: jeans3,
  //     name: "Casual Jeans 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["M", "L", "XL"],
  //     color: ["blue", "black"],
  //     gender: "male",
  //     price: 95,
  //   },
  //   {
  //     id: "36",
  //     img: jeans4,
  //     name: "Casual Jeans 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["M", "L", "XL"],
  //     color: ["blue", "black"],
  //     gender: "female",
  //     price: 100,
  //   },
  //   {
  //     id: "37",
  //     img: jeans5,
  //     name: "Casual Jeans 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["M", "L", "XL"],
  //     color: ["blue", "black"],
  //     gender: "female",
  //     price: 200,
  //   },
  //   {
  //     id: "37",
  //     img: jeans6,
  //     name: "Casual Jeans 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["S", "L", "XL"],
  //     color: ["blue", "black"],
  //     gender: "female",
  //     price: 200,
  //   },
  //   {
  //     id: "38",
  //     img: jeans7,
  //     name: "Casual Jeans 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["M", "L", "XL"],
  //     color: ["blue", "black"],
  //     gender: "male",
  //     price: 180,
  //   },
  //   {
  //     id: "39",
  //     img: jeans8,
  //     name: "Casual Jeans 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jeans",
  //     size: ["M", "L", "XL"],
  //     color: ["blue", "black"],
  //     gender: "male",
  //     price: 160,
  //   },
  //   {
  //     id: "40",
  //     img: jacket1,
  //     name: "Casual Jacket 1",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["M", "L", "XL"],
  //     color: ["black", "blue"],
  //     gender: "male",
  //     price: 400,
  //   },
  //   {
  //     id: "41",
  //     img: jacket2,
  //     name: "Casual Jacket 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["S", "L", "XL"],
  //     color: ["gray", "brown"],
  //     gender: "male",
  //     price: 255,
  //   },
  //   {
  //     id: "42",
  //     img: jacket3,
  //     name: "Casual Jacket 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["S", "M"],
  //     color: ["gray", "brown"],
  //     gender: "male",
  //     price: 300,
  //   },
  //   {
  //     id: "43",
  //     img: jacket4,
  //     name: "Casual Jacket 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["S", "M", "L"],
  //     color: ["gray", "brown"],
  //     gender: "male",
  //     price: 185,
  //   },
  //   {
  //     id: "44",
  //     img: jacket5,
  //     name: "Casual Jacket 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["S", "M", "L"],
  //     color: ["gray", "brown"],
  //     gender: "female",
  //     price: 185,
  //   },
  //   {
  //     id: "45",
  //     img: jacket6,
  //     name: "Casual Jacket 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["S", "M", "XL"],
  //     color: ["gray", "brown", "black"],
  //     gender: "male",
  //     price: 285,
  //   },
  //   {
  //     id: "46",
  //     img: jacket7,
  //     name: "Casual Jacket 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["S", "M", "XL"],
  //     color: ["brown", "black"],
  //     gender: "female",
  //     price: 425,
  //   },
  //   {
  //     id: "47",
  //     img: jacket8,
  //     name: "Casual Jacket 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Jackets",
  //     size: ["M", "L", "XL"],
  //     color: ["yellow", "orange", "blue"],
  //     gender: "female",
  //     price: 335,
  //   },
  //   {
  //     id: "48",
  //     img: bag1,
  //     name: "Casual Bag 1",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["black", "blue", "red"],
  //     gender: "female",
  //     price: 500,
  //   },
  //   {
  //     id: "49",
  //     img: bag2,
  //     name: "Casual Bag 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["green", "red", "blue"],
  //     gender: "male",
  //     price: 85,
  //   },
  //   {
  //     id: "50",
  //     img: bag3,
  //     name: "Casual Bag 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["brown", "blue", "orange"],
  //     gender: "female",
  //     price: 200,
  //   },
  //   {
  //     id: "51",
  //     img: bag4,
  //     name: "Casual Bag 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["brown", "blue", "orange"],
  //     gender: "female",
  //     price: 25,
  //   },
  //   {
  //     id: "52",
  //     img: bag5,
  //     name: "Casual Bag 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["yellow", "blue", "black"],
  //     gender: "female",
  //     price: 40,
  //   },
  //   {
  //     id: "53",
  //     img: bag6,
  //     name: "Casual Bag 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["blue", "black", "orange"],
  //     gender: "female",
  //     price: 400,
  //   },
  //   {
  //     id: "54",
  //     img: bag7,
  //     name: "Casual Bag 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["blue", "black", "orange"],
  //     gender: "female",
  //     price: 355,
  //   },
  //   {
  //     id: "55",
  //     img: bag8,
  //     name: "Casual Bag 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Bags",
  //     color: ["blue", "green", "red"],
  //     gender: "female",
  //     price: 100,
  //   },
  //   {
  //     id: "56",
  //     img: suit1,
  //     name: "Casual Suit 1",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["S", "M", "L"],
  //     color: ["black", "gray", "orange"],
  //     gender: "male",
  //     price: 300,
  //   },
  //   {
  //     id: "57",
  //     img: suit2,
  //     name: "Casual Suit 2",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["S", "M", "L"],
  //     color: ["purple", "orange", "gray"],
  //     gender: "male",
  //     price: 400,
  //   },
  //   {
  //     id: "58",
  //     img: suit3,
  //     name: "Casual Suit 3",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["M", "L", "XL"],
  //     color: ["purple", "orange", "gray"],
  //     gender: "male",
  //     price: 200,
  //   },
  //   {
  //     id: "59",
  //     img: suit4,
  //     name: "Casual Suit 4",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["L", "XL"],
  //     color: ["brown", "orange", "black"],
  //     gender: "male",
  //     price: 600,
  //   },
  //   {
  //     id: "60",
  //     img: suit5,
  //     name: "Casual Suit 5",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["L", "XL"],
  //     color: ["black", "blue", "red"],
  //     gender: "male",
  //     price: 750,
  //   },
  //   {
  //     id: "61",
  //     img: suit6,
  //     name: "Casual Suit 6",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["S", "M"],
  //     color: ["brown", "orange", "black"],
  //     gender: "female",
  //     price: 385,
  //   },
  //   {
  //     id: "62",
  //     img: suit7,
  //     name: "Casual Suit 7",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["L", "XL"],
  //     color: ["red", "blue", "black"],
  //     gender: "male",
  //     price: 700,
  //   },
  //   {
  //     id: "63",
  //     img: suit8,
  //     name: "Casual Suit 8",
  //     text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
  //     type: "Suits",
  //     size: ["S", "M", "XL"],
  //     color: ["blue", "green", "brown"],
  //     gender: "male",
  //     price: 550,
  //   },
  ];
  